### ISSUE TITLE
SSL Connection Error

### ISSUE THREAD

**Issue by cgpeltier** [datadesk/nasa-wildfires#15]
Hi, this library looks great, but I am receiving SSL connection errors:

```
import nasa_wildfires
data = nasa_wildfires.get_modis()
```
Returns:
```
SSLError: HTTPSConnectionPool(host='firms.modaps.eosdis.nasa.gov', port=443): Max retries exceeded with url: /data/active_fire/modis-c6.1/csv/MODIS_C6_1_Global_24h.csv (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)')))
```

**Comment by palewire** [comment]
Interesting, the scheduled github actions seem to be going okay.

https://github.com/datadesk/nasa-wildfires/actions

What could it be you think?

**Comment by cgpeltier** [comment]
Just wanted to update that I got around it by adding `verify = False` to the `requests.get()` call. Thanks!
