### ISSUE TITLE
Failed to load resource: net::ERR_FAILED

### ISSUE THREAD

**Issue by vnfrms** [datadesk/nasa-wildfires#19]
I am trying to use nasa-wildfires for "southern-africa" but could not success with my Google App Engine. My browser always shows "Failed to load resource: net::ERR_FAILED" and I think that the GeoJSON format generated from this nasa-wildfires is incorrect, with strange characters like "%20&#34;". 
Please help. 
Thank you in advance.

**Comment by palewire** [comment]
Can you share the code snippet you are running?

**Comment by vnfrms** [comment]
Just in DEV environment: 

hotspot_data = nasa_wildfires.get_viirs_suomi(region="southern-africa", time_range="7d")

return render_template('fire_hist_en.html',
			hotspot = hotspot_data,
			)

**Comment by vnfrms** [comment]
I am sorry. The output from Python print is perfect. It shall be issue with my JS script that read the data. Please ignore my issue posted. I will try my part. 
Thank you!

**Comment by palewire** [comment]
No problem. Good luck with your project.
