### ISSUE TITLE
Failure to Acquire Wildfire Data

### ISSUE THREAD

**Issue by nowak-mg** [datadesk/nasa-wildfires#24]
Am not completely sure why, but I have been receiving this Traceback for the past few days:

![image](https://github.com/datadesk/nasa-wildfires/assets/129254714/f8c6cbb9-b353-4cc7-a449-79861326e7a9)

The Traceback occurs with both the previous (1.1.0) and most recent version of nasa-wildfires (1.1.1). Any assistance that can be provided is much appreciated.

**Comment by palewire** [comment]
I got reports of the same issue from other user. That's why I came in yesterday and pushed out a new release. Believe it or not, the downloads were working just fine at that time.

I'm starting to think this is a problem with our source website. I wonder if it is flaking out and crashing from time to time.

**Comment by palewire** [comment]
We have our answer at https://firms.modaps.eosdis.nasa.gov/active_fire/
<img width="944" alt="Screen Shot 2023-07-25 at 2 29 38 PM" src="https://github.com/datadesk/nasa-wildfires/assets/9993/d6633d47-3fec-4b82-be0c-6a7dd87107d0">
I will update the URL and issue a new release.

**Comment by palewire** [comment]
Okay. I've released a new version, 1.2.0. It round robins between the two NASA servers and introduces and auto retry method if one fails. Give it a shot and let me know how it goes.

**Comment by nowak-mg** [comment]
Thank you so much for your quick response. I sometimes forget to check the source website... Version 1.2.0 works without issue for me now. It is a very nice fix.

**Comment by palewire** [comment]
👍
